---
# tasks file for config_leaf_vpc
- name: VPC - CREATE VPC KEEPALIVE VRF
  nxos_vrf:
    name: "{{ item.pkl_vrf }}"
  with_items:
    - "{{ vpc_interface }}"

- name: VPC - CONFIGURE VPC KEEPALIVE INTERFACE AS L3
  nxos_interface:
    name: "{{ item.keep_alive_interface }}"
    description: "{{ item.description }}"
    mode: layer3
  with_items:
    - "{{ vpc_interface }}"

- name: ADD VPC KEEPALIVE INTERFACE TO VRF KEEPALIVE
  nxos_config:
    lines:
      - vrf member keepalive
    parents: interface {{ item.keep_alive_interface }}
  with_items:
    - "{{ vpc_interface }}"

- name: ADD IPV4 ADDRESSES TO VPC KEEPALIVE INTERFACE
  nxos_l3_interface:
    name: "{{ item.keep_alive_interface }}"
    ipv4: "{{ item.ipv4 }}"
  with_items:
    - "{{ vpc_interface }}"

- name: VPC - CREATE PORTCHANNEL INTERFACE
  nxos_interface:
    name: "Port-channel999"
    description: "Port-Channel interface 999 for VPC 999"

- name: VPC - CONFIGURE PORTCHANNEL AS L2 TRUNK
  nxos_l2_interface:
    name: "{{ item.interface }}"
    mode: trunk
    native_vlan: 1
  with_items:
    - "{{ vpc_interface }}"

- name: VPC - ADD MEMBERS TO PORTCHANNEL
  nxos_linkagg:
      group: "999"
      force: true
      min_links: 1
      members:
        - Ethernet1/6
        - Ethernet1/7
      mode: "active"
  with_items:
    - "{{ vpc_interface }}"

- name: CONFIGURE VPC
  nxos_vpc:
    domain: "{{ item.domain }}"
    role_priority: "{{ item.role_priority }}"
    pkl_dest: "{{ item.pkl_dest }}"
    pkl_src: "{{ item.pkl_src }}"
    pkl_vrf: "{{ item.pkl_vrf }}"
    peer_gw: "{{ item.peer_gw }}"
    auto_recovery: "{{ item.auto_recovery }}"
  with_items:
    - "{{ vpc_interface }}"

- name: CONFIGURE VPC INTERFACE
  nxos_vpc_interface:
    portchannel: "{{ item.domain }}"
    peer_link: true
  with_items:
    - "{{ vpc_interface }}"
