---
# tasks file for test_connection

- name: Gather facts from NXOS devices using nxos_facts
  nxos_facts:
    gather_subset:
      - all
      - "!config"
  tags: facts_only

- name: Display Serial Number of the device gathered from ansible_net_serialnum fact
  debug:
    msg: DEVICE {{ansible_net_hostname}}, MODEL {{ansible_net_model}}, SERIAL {{ansible_net_serialnum}}, VERSION {{ansible_net_version}}

- name: Gather show clock
  nxos_command:
    commands: show clock
  register: show_clock_output

- name: Debug
  debug:
    msg: {{ show_clock_output.stdout_lines }}