---
# tasks file for test_connection

#- name: Gather facts from NXOS devices using nxos_facts
#  nxos_facts:
#    gather_subset:
#      - all
#      - "!config"
#  tags: facts_only

#- name: Display Serial Number of the device gathered from ansible_net_serialnum fact
#  debug:
#    msg: DEVICE {{ansible_net_hostname}}, MODEL {{ansible_net_model}}, SERIAL {{ansible_net_serialnum}}, VERSION {{ansible_net_version}}

#- name: Gather show clock
 # nxos_command:
#    commands: show clock
#  register: show_clock_output

#- name: Debug
#  debug:
#    msg: "{{ show_clock_output.stdout_lines }}"

####### 

- name: Precheck with vars in this role
  nxos_command:
    commands: "{{ item }}"
  with_items: "{{ precheck }}"
  register: precheck_output
  no_log: True

#- set_fact:
#    precheck_reg: "{{ precheck_output.results }}"

- name: SHOW RESULTS
  debug:
    var: "{{ item.stdout_lines }}"
  with_items: "{{ precheck_output.results[0] }}"

#- set_fact: 
#    show_clock: "{{ precheck_vars.results[0].stdout_lines }}"
#    show_ip_int: "{{ precheck_vars.results[1].stdout_lines }}"



#- name: Debug show_ip_int
#  debug:
#    var: show_ip_int

###### 
#- name: Precheck with file
#  nxos_config:
#    src: files/precheck_file
#  register: precheck_file_cmd
#
#- debug:
#    msg: "{{ precheck_file_cmd }}"