---
mgmt_interface:
  - { interface: "mgmt0", description: "MTGT SWITCH Ethernet2", ipv4: "192.168.122.22/24" }

loopback_interfaces:
  - { interface: "Loopback0", description: "Loopback0 for local VTEP IP, and BGP", ipv4: "40.1.1.1/32" }

vlan_interfaces:
  - { interface: "Vlan1001", description: "Server facing SVI", ipv4: "4.1.1.3/24", ipv6: "4:1:0:1::1/64", vrf_member: "vxlan-900001" }
  - { interface: "Vlan1002", description: "Server facing SVI", ipv4: "4.2.2.3/24", ipv6: "4:2:0:1::1/64", vrf_member: "vxlan-900001" }

l2_interfaces:
  - { interface: "Ethernet1/1", description: "Server facing Interfaces", mode: "access", access_vlan: "1002", vrf_member: "" }
  - { interface: "Ethernet1/2", description: "Server facing Interfaces", mode: "access", access_vlan: "1001", vrf_member: "" }

l3_interfaces:
  - { interface: "Ethernet1/8", description: "Spine-leaf interconnect spine01", ipv4: "192.168.2.18/24", vrf_member: "" }
  - { interface: "Ethernet1/9", description: "Spine-leaf interconnect spine02", ipv4: "192.168.4.19/24", vrf_member: "" }
  - { interface: "Vlan1001", description: "Server facing SVI", ipv4: "4.1.1.1/24", ipv6: "4:1:0:1::1/64", vrf_member: "vxlan-900001" }
  - { interface: "Vlan1002", description: "Server facing SVI", ipv4: "4.2.2.1/24", ipv6: "4:2:0:1::1/64", vrf_member: "vxlan-900001" }

l3_ospf_uplink_interfaces:
  - { interface: "Ethernet1/8", description: "Spine-leaf interconnect spine01", ipv4: "192.168.2.18/24", vrf_member: "" }
  - { interface: "Ethernet1/9", description: "Spine-leaf interconnect spine02", ipv4: "192.168.4.19/24", vrf_member: "" }

anycast_gw_interfaces:
  - { interface: "Vlan1001" }
  - { interface: "Vlan1002" }

control_vlan_interface:
  - { interface: "Vlan101", description: "Internal control VLAN/SVI for the VRF", mode: "access", access_vlan: "101", vrf_member: "vxlan-900001" }

port_channel_interfaces:
  - { interface: "Ethernet1/6", description: "Portchannel interface 1/6", channel_group: "99", vrf_member: "" }
  - { interface: "Ethernet1/7", description: "Portchannel interface 1/6", channel_group: "99", vrf_member: "" }
