---
# tasks file for config_spine_interfaces

- name: CONFIGURE ETHERNET INTERFACES AS L3
  nxos_interface:
    name: "{{ item.interface }}"
    description: "{{ item.description }}"
    mode: layer3
    mtu: 9216
  with_items:
    - "{{ l3_interfaces }}"

- name: CONFIGURE LOOPBACK INTERFACES AS L3
  nxos_interface:
    name: "{{ item.interface }}"
    description: "{{ item.description }}"
    mode: layer3
  with_items:
    - "{{ loopback_interfaces }}"

- name: ADD IP ADDRESSES TO LOOPBACK INTERFACES
  nxos_l3_interface:
    name: "{{ item.interface }}"
    ipv4: "{{ item.ipv4 }}"
    state: present
  with_items:
    - "{{ loopback_interfaces }}"

- name: MAKE LEAF-SPINE INTERFACES POINT-TO-POINT NETWORKS
  nxos_config:
    lines: 
      - medium p2p
    parents: 
      - interface {{ item.interface }}
  with_items:
    - "{{ l3_interfaces }}"

- name: MAKE LEAF-SPINE INTERFACES IP UNNUMBERED TO LOOPBACK0
  nxos_config:
    lines: 
      - ip unnumbered loopback0
    parents: 
      - interface {{ item.interface }}
  with_items:
    - "{{ l3_interfaces }}"