---
# tasks file for config_leaf_bgp
- name: ENSURE BGP ASN EXISTS
  nxos_bgp:
    asn: "{{ bgp_asn }}"
    router_id: "{{ bgp_router_id }}"

- name: BGP NEIGHBOR CONFIG
  nxos_bgp_neighbor:
    asn: "{{ bgp_asn }}"
    neighbor: "{{ item.neighbor }}"
    remote_as: "{{ item.remote_as }}"
    update_source: "Loopback0"
  with_items: "{{ bgp_neighbors }}"

- name: ADD VRF TO BGP AF
  nxos_bgp_af:
    asn: "{{ bgp_asn }}"
    vrf: "{{ item.interface }}"
    afi: "{{ item.afi }}"
    safi: "{{ item.safi }}"
    advertise_l2vpn_evpn: true
    state: present
  with_items: "{{ bgp_interfaces }}"

- name: CONFIGURE L2VPN UNICAST ADDRESS FAMILY
  nxos_bgp_neighbor_af:
    asn: "{{ bgp_asn }}"
    neighbor: "{{ item.neighbor }}"
    afi: l2vpn
    safi: evpn
    send_community: both
    route_reflector_client: false
  with_items: "{{ bgp_neighbors }}"